// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcVNtwIkNsM0LB5109o704t1ZpBA_6k8o',
    appId: '1:340466285651:web:5e2aeb4cf0adbc6adcdaa6',
    messagingSenderId: '340466285651',
    projectId: 'quranapp-487bc',
    authDomain: 'quranapp-487bc.firebaseapp.com',
    storageBucket: 'quranapp-487bc.appspot.com',
    measurementId: 'G-NSCFJC6YV9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYOVP6Oyhp3f1U6lU8Sd5R9tP4gmBGUBA',
    appId: '1:340466285651:android:7d6db9ba561e98a9dcdaa6',
    messagingSenderId: '340466285651',
    projectId: 'quranapp-487bc',
    storageBucket: 'quranapp-487bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe4gmyNpdA4IQcwokvgThmHwNuGfRwPGw',
    appId: '1:340466285651:ios:f4037b066672c3a0dcdaa6',
    messagingSenderId: '340466285651',
    projectId: 'quranapp-487bc',
    storageBucket: 'quranapp-487bc.appspot.com',
    iosClientId: '340466285651-t0apbfp0pms8aejkeevjm24e1p4ndck2.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe4gmyNpdA4IQcwokvgThmHwNuGfRwPGw',
    appId: '1:340466285651:ios:1d3d16dc3a807a67dcdaa6',
    messagingSenderId: '340466285651',
    projectId: 'quranapp-487bc',
    storageBucket: 'quranapp-487bc.appspot.com',
    iosClientId: '340466285651-v3amttj958dvssf7m70opm6l58o6b287.apps.googleusercontent.com',
    iosBundleId: 'com.example.quranApp.RunnerTests',
  );
}
